name: Trivy

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${GITHUB_REPOSITORY}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os
          severity: CRITICAL,HIGH